version: '3.9'
services:
  db:
    image: timescale/timescaledb:latest-pg15            # Official PG15 + Timescale
    environment:
      POSTGRES_DB: videosync
      POSTGRES_USER: vsync_dev
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
